### ISSUE TITLE
Support defining roles per key

### ISSUE THREAD

**Issue by johnknl** [kleijnweb/jwt-bundle#5]
Eg:

``` yaml
jwt:
   keys:
      admin: 
        secret: 'A Pre-Shared Key'
        roles: [ROLE_ADMIN]
```
